import { test, expect } from '@playwright/test';
import { users, baseUrl } from '@config/users.config';
import { config } from '@config/test.config';
import { LoginPage, InvoicePage, LicensePage, PortalShopPage, ScheduledActionPage } from '@pages';
import type { ScheduledActionState } from '@pages';
import { CommonUtils } from '@helpers/common.utils';

/**
 * =================================================================================================
 *  CRM-12501 - Perpetual licences stamped with a 365-day expiry
 *  TC 7.1.4 - WebShop path: a perpetual licence generated automatically from a paid order carries
 *             no expiry  (the ticket's MAIN case - Test case 4)
 * =================================================================================================
 *  Test Case ID    : CRM-12501_7.1.4
 *  Jira            : CRM-12501
 *  Automation-Type : new
 *  Automation-Date : 2026-09-10
 *
 *  Summary:
 *    As the Bronze reseller, buys a perpetual licence on the partner-portal WebShop (/shop calculator ->
 *    new end user -> Stripe test card), fires the automatic generation job ("License Manager: Website
 *    Invoice to License" > RUN MANUALLY - disabled on pre-production) and asserts the licence Odoo
 *    generated on its own carries no expiry.
 *
 *  Command to run:
 *    npx playwright test --grep "CRM-12501_7\.1\.4:" --project=chromium
 *
 * -------------------------------------------------------------------------------------------------
 *  Source manual TC - CRM-12501, dev comment of 2026-09-07 17:56 (+03:00), Test case 4
 *                     "a perpetual licence generated automatically from a paid WebShop order no
 *                     longer carries an expiry" -> VERIFIED PASS by the reporter on 2026-09-08 09:57
 *                     (+03:00), who named it "the main focus of this ticket".
 * -------------------------------------------------------------------------------------------------
 *  Pre-condition(s)
 *    1. Log in to the partner portal as the Bronze reseller (users.reseller_bronze).
 *    2-9. Place a paid perpetual order on the WebShop ("BUY NEW LICENSE"):
 *       open /shop (pass the "new end users only" notice); on the licence calculator pick
 *       Licence type = Perpetual, Sockets = 2, Edition = Enterprise Essentials (= SKU [A2144B],
 *       $329 x 2, minus the Bronze partner discount); Next (this creates the website Sale Order);
 *       on "End user details" enter the new end user; Next; on "Checkout" confirm the order named
 *       "Your order: SO######" has a positive total, select the Stripe acquirer, type the Stripe test
 *       card 4242 4242 4242 4242, 12/29, 123, 10001; Pay; wait for the order confirmation.
 *
 *       Calculator values (one per line):
 *         - Licence type   = Perpetual
 *         - Sockets        = 2
 *         - Edition        = Enterprise Essentials       (-> [A2144B], licensing = perpetual, template 8276)
 *         - Support        = Standard, 1 year            (calculator defaults)
 *         - Currency       = USD                         (calculator default)
 *       End user details (one per line):
 *         - First name     = Test
 *         - Last name      = EndUser <timestamp>
 *         - Email          = Test@company<timestamp>.com
 *         - Phone          = +1 408 555 0100
 *         - Company        = TEST WebShop Co <timestamp>
 *         - Address Line 1 = 1639 Little Terrace
 *         - City           = Hartford
 *         - ZIP            = 06103
 *         - Country        = United States               (res.country 233)
 *         - State          = Connecticut
 *    10-11. Read the website invoice the payment created: portal My invoices -> newest invoice -> its
 *       backend id from the portal URL.
 *
 *  Steps to reproduce #1
 *    1. A paid perpetual-product order processed through the automatic WebShop generation, the same
 *       path that produced the reported licence.
 *       (Folded into this step - mechanical actions only: as admin, open Scheduled Action id 37
 *       "License Manager: Website Invoice to License" in developer mode and press RUN MANUALLY, then
 *       open the invoice's "License" stat button to reach the licence the job generated.)
 *
 *  Verification
 *    - The automatically generated licence is Perpetual with Expires = never and expiration days = 0.
 *    - Reporter's recognition marks (confirmation of 2026-09-08): Installer provider = Nakivo and
 *      Generated by Odoo = True; Expire Mode = none; no Expire Start Date and no Expiration End Date.
 *
 * -------------------------------------------------------------------------------------------------
 *  Why the WebShop order and not a back-office invoice paid on the portal - grounded 2026-09-10
 * -------------------------------------------------------------------------------------------------
 *  The job takes only invoices the WEBSITE created. Both invoices the dev's manual run picked (197094,
 *  195760) have `create_uid = 1 (NAKIVO, Inc.)`, and 195760's order SO197627 carries
 *  `website_id = NAKIVO Partner Portal`. A Thomas-created deal-registration invoice paid on the portal
 *  (INV/2026/2649, run of 14:45) was ignored by RUN MANUALLY twice. The reported licence #146359 came
 *  from webshop order SO192332 (website_id = 1, Stripe transaction on the ORDER, invoice auto-created
 *  by uid 1 on confirmation, licence 15m43s later = one cron tick).
 *
 *  The WebShop is the nakivo_shop calculator behind "BUY NEW LICENSE" on /shop (the standard
 *  website_sale catalog is empty - no product.template is website_published). Its Next rebuilds the
 *  reseller's cart Sale Order from scratch each time (all lines share one create_date), so no cart
 *  clean-up is needed. Screens: /shop -> /shop/address -> /shop/payment (form /shop/payment/token,
 *  Stripe radio pm_id = new_8, button #o_payment_form_pay "Pay").
 *
 *  KNOWN BLOCKER (2026-09-10): pre-production carries leftover promotion programs named
 *  "TEST- 2-1-1-x <timestamp>" / "TEST- Order - 10% ..." (Discount-suite runs of 2026-09-05..07) that
 *  auto-apply to every website order - a 2-socket [A2144B] cart ($658) ended at -542.38 with 15 discount
 *  lines, and Stripe cannot charge a negative total. The spec therefore ASSERTS the order total is
 *  positive before pressing Pay and fails loudly with the order summary, so the pollution is diagnosed
 *  in one line instead of a Stripe error. Archive those programs (or ask the Discount suite owner to)
 *  and the flow proceeds.
 *  The same pollution makes every shop request recompute 31 programs over the 16-line cart: on
 *  2026-09-10 the calculator "Next" was silently dropped in 3 of 5 runs, and when it did go through
 *  the intermediate /shop/confirm_order step took minutes before redirecting to /shop/payment.
 *  PortalShopPage waits for the network to settle before pressing Next, retries once with Enter and
 *  once through the form's own submit, and gives the redirect the full page-load budget - but a clean
 *  cart on a clean pre-production is what makes this TC fast and deterministic.
 *
 * -------------------------------------------------------------------------------------------------
 *  Why RUN MANUALLY - grounded on pre-production, 2026-09-10
 * -------------------------------------------------------------------------------------------------
 *  Scheduled action id 37 "License Manager: Website Invoice to License" (`_cron_create_website_license`,
 *  every 15 minutes on Production) is DISABLED on pre-production (`active = false`, `nextcall` frozen at
 *  2026-01-22) and its server action 984 is bound to no menu, so the job is fired by hand from the
 *  developer-mode form `/web?debug=1#id=37&action=11&model=ir.cron&view_type=form&menu_id=4` - the same
 *  button the tester drove by hand. It runs once and stays disabled; the schedule is captured before and
 *  restored only if it moved.
 *
 * -------------------------------------------------------------------------------------------------
 *  UI grounding (form view 2441)
 * -------------------------------------------------------------------------------------------------
 *  `expiration_days` is rendered only when expires = 'in'; `expire_start_date` / `expiration_end_date`
 *  only when expire_mode = 'PER_LICENSE'. On a correct perpetual licence all three are ABSENT from the
 *  screen - asserted as such, plus the values read as empty-or-zero. "Installer provider" is the field
 *  `vendor`; "Generated by Odoo" is the readonly boolean `generated_by_odoo`. The dev's evidence licence
 *  #149605 (this exact path) reads: perpetual, expires = never, expire_mode = NONE, expiration_days = 0,
 *  dates empty, maintenance_days = 365.
 *
 * -------------------------------------------------------------------------------------------------
 *  Data & cleanup
 * -------------------------------------------------------------------------------------------------
 *  Fresh, uniquely timestamped end user every run (REQUIREMENT #2); the reseller and its portal login
 *  are fixed fixtures (users.config), as in CRM-12373_2 / CRM-12424_1. The licence the job generates is
 *  deleted in afterEach (Draft - the "Sent License" job is disabled too). The website order, its PAID
 *  invoice and Stripe transaction are left in place on purpose (a paid invoice cannot be removed without
 *  unreconciling and cancelling); their ids are printed at the end of the run.
 */

// --- Test data ------------------------------------------------------------------------------------
const TC_ID = 'CRM-12501_7.1.4';
const PERPETUAL_SKU = '[A2144B]';        // what "Enterprise Essentials, 2 sockets, perpetual" resolves to
const LICENSE_MODEL = 'license_management.license';
const INVOICE_MODEL = 'account.invoice';

const SHOP_LICENSE = { licenseType: 'perpetual' as const, sockets: 2, edition: 'enterprise_essentials' as const };
const US_COUNTRY_ID = '233';
const US_STATE = 'Connecticut';

// The automatic WebShop generation job (ir.cron 37 on pre-production).
const WEBSHOP_CRON_ID = 37;
const WEBSHOP_CRON_NAME = 'License Manager: Website Invoice to License';

// Portal payment - Stripe test mode (see CRM-12373_2): acquirer radio value "new_<payment.acquirer id>".
const STRIPE_ACQUIRER_VALUE = 'new_8';
const TEST_CARD = { number: '4242424242424242', expiry: '1229', cvc: '123', zip: '10001' };

// --- Expected generated state (perpetual => nothing expires) --------------------------------------
const EXPECTED_LICENSING = 'Perpetual';
const EXPECTED_EXPIRES = 'never';
const EXPECTED_EXPIRE_MODE = 'none';
const EXPECTED_INSTALLER_PROVIDER = 'Nakivo';

// --- Cleanup toggles (true = skip, false = run) ---------------------------------------------------
const SKIP_CLEANUP_LICENSE = false; // delete the licence the job generated
const SKIP_CLEANUP_CHAIN = true;    // website order / PAID invoice / Stripe transaction: see header

test.describe('CRM-12501_7.1 - Perpetual licence must not carry an expiry', () => {
  let licenseUrl = '';
  let licenseId = '';
  let orderName = '';
  let invoiceId = '';
  let invoiceNumber = '';

  test.beforeEach(async ({ context }) => {
    // Clear cookies to ensure a fresh session. No screenshot here: the page is still about:blank.
    await context.clearCookies();
    await CommonUtils.wait(CommonUtils.waitTimes.medium);
  });

  test.afterEach(async ({ page }, testInfo) => {
    await CommonUtils.captureAndAttachScreenshot(page, testInfo, 'afterEach - start').catch(() => {});

    if (testInfo.status === 'failed' || testInfo.status === 'timedOut') {
      const failureReason = testInfo.error?.message?.split('\n').slice(0, 8).join('\n').trim();
      if (failureReason) {
        console.log('TEST FAILED - reason:');
        console.log(`   ${failureReason.replace(/\n/g, '\n   ')}`);
      }
      await CommonUtils.waitForSpinnersToHide(
        page,
        CommonUtils.waitTimes.extraLong,
        CommonUtils.waitTimes.abnormalWait
      ).catch(() => {});
    }

    console.log('--- Records created by this run ---');
    console.log(`  - Licence      : ${licenseId ? `#${licenseId} - ${licenseUrl}` : '(not generated)'}`);
    console.log(`  - Website order: ${orderName || '(not created)'}`);
    console.log(`  - Invoice      : ${invoiceNumber ? `${invoiceNumber} (#${invoiceId})` : '(not created)'}`);

    if (!SKIP_CLEANUP_LICENSE && licenseUrl) {
      try {
        await CommonUtils.deleteRecordByUrl(page, licenseUrl, testInfo);
      } catch (error) {
        // Never fail a green test in teardown - report the leftover id instead (shared pre-prod).
        console.log(`  - Could not delete licence #${licenseId}: ${error instanceof Error ? error.message : String(error)}`);
        console.log(`  - LEFTOVER licence to remove manually: #${licenseId} - ${licenseUrl}`);
      }
    } else if (SKIP_CLEANUP_LICENSE) {
      console.log('  - Licence cleanup SKIPPED (SKIP_CLEANUP_LICENSE = true)');
    }

    if (SKIP_CLEANUP_CHAIN) {
      console.log('  - Chain cleanup SKIPPED (SKIP_CLEANUP_CHAIN = true) - paid website order cannot be deleted cleanly');
    }

    await CommonUtils.captureAndAttachScreenshot(page, testInfo, 'afterEach - teardown done').catch(() => {});
  });

  test('CRM-12501_7.1.4: Verify a perpetual licence generated automatically from a paid WebShop order carries no expiry', async ({ page }, testInfo) => {
    test.setTimeout(config.timeouts.test + CommonUtils.waitTimes.runningTestScript);
    await page.setViewportSize({ width: 1920, height: 1080 });

    const loginPage = new LoginPage(page);
    const invoicePage = new InvoicePage(page);
    const licensePage = new LicensePage(page);
    const shop = new PortalShopPage(page);
    const cronPage = new ScheduledActionPage(page);

    const stamp = CommonUtils.generateTimestamp();
    const endUser = {
      firstName: 'Test',
      lastName: `EndUser ${stamp}`,
      email: `Test@company${stamp}.com`,
      phone: '+1 408 555 0100',
      company: `TEST WebShop Co ${stamp}`,
      street: '1639 Little Terrace',
      city: 'Hartford',
      zip: '06103',
      countryId: US_COUNTRY_ID,
      stateName: US_STATE,
    };

    let orderTotal = NaN;
    let portalPaidUrl = '';
    let cronActionName = '';
    let runManuallyPressed = false;
    let licenseCountOnInvoice = 0;

    let licenseName = '';
    let generatedByOdoo = false;
    let installerProvider = '';
    let licensing = '';
    let expires = '';
    let expireMode = '';
    let expirationDaysShown = true;
    let expirationDays = '';
    let expireStartDateShown = true;
    let expireStartDate = '';
    let expirationEndDateShown = true;
    let expirationEndDate = '';
    let maintenanceDays = '';

    // -------------------------------------------------------------------------------------------
    // Pre-condition #1 - the reseller's portal session
    // -------------------------------------------------------------------------------------------
    await test.step('Pre-condition 1: Log in to the partner portal as the Bronze reseller', async () => {
      await loginPage.navigateTo(baseUrl);
      await loginPage.loginPortalUser(users.reseller_bronze.username, users.reseller_bronze.password);
      await shop.waitForPortalReady();
      console.log(`  - Logged in to the portal as ${users.reseller_bronze.displayName} (${users.reseller_bronze.level})`);
      await CommonUtils.captureAndAttachScreenshot(page, testInfo, 'Pre-condition I - portal session as the Bronze reseller');
    });

    // -------------------------------------------------------------------------------------------
    // Pre-condition #2 (steps 2-9) - the paid WebShop order
    // -------------------------------------------------------------------------------------------
    await test.step(`Pre-condition 2-9: Place a paid perpetual order on the WebShop (Enterprise Essentials, 2 sockets = ${PERPETUAL_SKU})`, async () => {
      const onCalculator = await shop.openShop();
      expect(onCalculator, 'The /shop licence calculator must be on screen ("BUY NEW LICENSE" flow)').toBe(true);

      const cfg = await shop.configureLicense(SHOP_LICENSE);
      console.log(`  - Licence type   : ${SHOP_LICENSE.licenseType}`);
      console.log(`  - Sockets        : ${cfg.sockets}`);
      console.log(`  - Edition        : ${SHOP_LICENSE.edition}`);
      expect(cfg.licenseTypeChecked, 'The calculator must have "Perpetual" selected').toBe(true);
      expect(cfg.editionChecked, 'The calculator must have "Enterprise Essentials" selected - another edition buys another SKU').toBe(true);
      expect(cfg.sockets, 'The calculator must hold 2 sockets').toBe(String(SHOP_LICENSE.sockets));
      console.log(`  - Price summary  : ${await shop.getCalculatorSummary()}`);

      const nextStep = await shop.clickCalculatorNext();
      if (nextStep === 'address') {
        const address = await shop.fillEndUserAddress(endUser);
        console.log(`  - First name     : ${endUser.firstName}`);
        console.log(`  - Last name      : ${endUser.lastName}`);
        console.log(`  - Email          : ${endUser.email}`);
        console.log(`  - Phone          : ${endUser.phone}`);
        console.log(`  - Company        : ${endUser.company}`);
        console.log(`  - Address Line 1 : ${endUser.street}`);
        console.log(`  - City           : ${endUser.city}`);
        console.log(`  - ZIP            : ${endUser.zip}`);
        console.log(`  - Country        : United States (${address.countryId})`);
        console.log(`  - State          : ${US_STATE} (${address.stateId})`);
        expect(address.countryId, 'The address form must hold the United States country id').toBe(US_COUNTRY_ID);
        expect(address.stateId, 'The address form must hold a state id').not.toBe('');
        await shop.clickAddressNext();
      } else {
        // The reseller's cart already carried an end user (left by an earlier run), so the shop went
        // straight to Checkout. The order is still a fresh website order for this run; only the end
        // user is reused - logged so the report shows it.
        console.log('  - End user       : reused from the reseller\'s existing cart (shop skipped the address step)');
      }

      orderName = await shop.getOrderNameOnPaymentPage();
      const summary = await shop.getOrderSummaryOnPaymentPage();
      orderTotal = await shop.getOrderTotalOnPaymentPage();
      console.log(`  - Website order  : ${orderName || '(not shown)'}`);
      console.log(`  - Order summary  : ${summary.slice(0, 600)}`);
      expect(orderName, 'The checkout page must name the website Sale Order ("Your order: SO######")').toMatch(/^SO\d+$/);
      expect(summary, `The order must carry the perpetual SKU ${PERPETUAL_SKU}`).toContain(PERPETUAL_SKU);
      expect(orderTotal, `The order total must be a positive amount before paying - a zero/negative total means leftover promotion programs are eating the cart (see header). Summary: ${summary.slice(0, 400)}`)
        .toBeGreaterThan(0);

      const acquirer = await shop.selectStripeOnShopPayment();
      expect(acquirer, `The checkout must offer the Stripe acquirer ("${STRIPE_ACQUIRER_VALUE}")`).toBe(STRIPE_ACQUIRER_VALUE);
      const cardEcho = await shop.fillStripeCardDetails(TEST_CARD);
      const digits = (s: string) => s.replace(/\D/g, '');
      expect(digits(cardEcho.number), 'Stripe must hold the full card number that was typed').toBe(TEST_CARD.number);
      expect(digits(cardEcho.expiry), 'Stripe must hold the full expiry date that was typed').toBe(TEST_CARD.expiry);
      expect(digits(cardEcho.cvc), 'Stripe must hold the full CVC that was typed').toBe(TEST_CARD.cvc);

      await shop.clickShopPay();
      const navigatedTo = await shop.waitForPaymentToLeaveTheForm();
      const paymentError = navigatedTo ? '' : await shop.getPortalPaymentError();
      console.log(`  - Navigated to   : ${navigatedTo || '(no navigation)'}`);
      console.log(`  - Payment error  : ${paymentError || '(none)'}`);
      expect(paymentError, `The shop / Stripe must report no payment error, got "${paymentError}"`).toBe('');
      const confirmation = await shop.waitForShopOrderConfirmation();
      portalPaidUrl = confirmation.url;
      console.log(`  - Confirmation   : ${confirmation.text.slice(0, 300)}`);
      expect(portalPaidUrl, 'The payment must leave /shop/payment and /payment/process').not.toMatch(/\/shop\/payment|\/payment\/process/);

      await CommonUtils.captureAndAttachScreenshot(page, testInfo, `Pre-condition II - WebShop order ${orderName} paid`);
    });

    // -------------------------------------------------------------------------------------------
    // Pre-condition #3 (steps 10-11) - the website invoice the payment created
    // -------------------------------------------------------------------------------------------
    await test.step('Pre-condition 10-11: Read the website invoice the payment created (portal My invoices, newest)', async () => {
      await shop.gotoMyInvoices();
      const numbers = await shop.getListedInvoiceNumbers();
      console.log(`  - Newest portal invoices: ${numbers.slice(0, 3).join(', ') || '(none)'}`);
      expect(numbers.length, 'The reseller must see at least one invoice after paying the WebShop order').toBeGreaterThan(0);
      invoiceNumber = numbers[0];
      await shop.openInvoiceByNumber(invoiceNumber);
      invoiceId = shop.invoiceIdFromPortalUrl(shop.getCurrentUrl());
      const paidShown = await shop.isInvoicePaidMessageShown(CommonUtils.waitTimes.abnormalWait).catch(() => false);
      console.log(`  - Invoice        : ${invoiceNumber} (#${invoiceId}) - portal reports paid: ${paidShown}`);
      let __verifyPassed = false;
      try {
        expect(invoiceId, 'The portal invoice URL must carry the backend invoice id').not.toBe('');
        expect(paidShown, `The website invoice ${invoiceNumber} must be paid - the job only picks up PAID invoices`).toBe(true);
        __verifyPassed = true;
      } finally {
        await CommonUtils.captureVerifyEvidence(page, testInfo, { name: `Pre-condition III - website invoice ${invoiceNumber} paid - verify`, passed: __verifyPassed }).catch(() => {});
      }
    });

    // -------------------------------------------------------------------------------------------
    // Steps to reproduce #1
    // -------------------------------------------------------------------------------------------
    await test.step('Step 1: A paid perpetual-product order processed through the automatic WebShop generation, the same path that produced the reported licence', async () => {
      // Admin in the same context.
      await loginPage.logout(baseUrl);
      await page.context().clearCookies();
      await loginPage.navigateTo(baseUrl);
      await loginPage.login(users.admin_crm.username, users.admin_crm.password);
      await loginPage.dismissLocationPermissionDialog().catch(() => {});
      console.log('  - Logged in as admin CRM');

      // Fire the automatic WebShop generation once (the job is disabled on pre-production).
      const opened = await cronPage.openScheduledActionById(WEBSHOP_CRON_ID);
      expect(opened, `Scheduled action #${WEBSHOP_CRON_ID} must open in developer mode`).toBe(true);
      cronActionName = await cronPage.getActionName();
      console.log(`  - Scheduled action: "${cronActionName}"`);
      expect(cronActionName, `Scheduled action #${WEBSHOP_CRON_ID} must be "${WEBSHOP_CRON_NAME}"`)
        .toContain(WEBSHOP_CRON_NAME);

      let cronState: ScheduledActionState | null = null;
      try {
        cronState = await cronPage.readState();
        const runManuallyVisible = await cronPage.isRunManuallyVisible();
        expect(runManuallyVisible, 'The "RUN MANUALLY" button must be rendered (developer mode + Technical Features)').toBe(true);
        runManuallyPressed = await cronPage.clickRunManually();
        expect(runManuallyPressed, '"RUN MANUALLY" must be pressed so the WebShop generation runs once').toBe(true);
      } finally {
        // Shared-environment rule: never leave the job's schedule changed. RUN MANUALLY does not touch
        // the schedule, so restore ONLY when the state really moved.
        if (cronState) {
          const before = cronState;
          const after = await cronPage.readState().catch(() => null);
          const moved = !after || after.nextExecution !== before.nextExecution;
          if (moved) {
            console.log(`  - Cron schedule moved ("${before.nextExecution}" -> "${after ? after.nextExecution : '?'}") - restoring`);
            await cronPage.restoreState(before).catch((error) => {
              console.log(`  WARN: cron state restore FAILED - set "Next Execution Date" back to "${before.nextExecution}" by hand (${error instanceof Error ? error.message.split('\n')[0] : String(error)})`);
            });
          } else {
            console.log(`  - Cron schedule unchanged (Next Execution "${after?.nextExecution}") - no restore needed`);
          }
        }
      }

      // The job generated the licence against the website invoice - reach it through the stat button.
      await invoicePage.openRecordFormById(baseUrl, INVOICE_MODEL, invoiceId);
      const sourceDocument = await invoicePage.getSourceDocument(CommonUtils.waitTimes.abnormalWait).catch(() => '');
      console.log(`  - Invoice ${invoiceNumber} source document: ${sourceDocument || '(empty)'}`);
      let __verifyPassed = false;
      try {
        expect(sourceDocument, `The website invoice must originate from the paid order ${orderName}`).toContain(orderName);
        licenseCountOnInvoice = await invoicePage.getLicenseSmartButtonCount();
        console.log(`  - Licences on invoice ${invoiceNumber}: ${licenseCountOnInvoice}`);
        expect(licenseCountOnInvoice, `The WebShop job must have generated exactly one licence for invoice ${invoiceNumber}`)
          .toBe(1);

        await invoicePage.clickLicenseSmartButton();
        await licensePage.waitForPageLoad(CommonUtils.waitTimes.pageLoad);
        licenseId = licensePage.getRecordIdFromUrl();
        expect(licenseId, 'The generated licence must open as a saved record (a record id must appear in the form URL)').not.toBe('');
        __verifyPassed = true;
      } finally {
        await CommonUtils.captureVerifyEvidence(page, testInfo, { name: 'Step 1: Invoice and licence data verified', passed: __verifyPassed }).catch(() => {});
      }
      licenseUrl = `${baseUrl.replace(/\/$/, '')}/web#id=${licenseId}&model=${LICENSE_MODEL}&view_type=form`;

      licenseName = await licensePage.getLicenseNameValue();
      generatedByOdoo = await licensePage.isGeneratedByOdooChecked();
      installerProvider = await licensePage.getInstallerProviderValue();
      licensing = await licensePage.getLicensingValue();
      expires = await licensePage.getExpiresValue();
      expireMode = await licensePage.getExpireModeValue();
      expirationDaysShown = await licensePage.isFieldDisplayed('expiration_days');
      expirationDays = await licensePage.getExpirationDaysValue();
      expireStartDateShown = await licensePage.isFieldDisplayed('expire_start_date');
      expireStartDate = await licensePage.getExpireStartDateValue();
      expirationEndDateShown = await licensePage.isFieldDisplayed('expiration_end_date');
      expirationEndDate = await licensePage.getExpirationEndDateValue();
      maintenanceDays = await licensePage.getMaintenanceDaysValue();

      console.log(`  - Licence generated: #${licenseId} - ${licenseUrl}`);
      console.log(`  - Name                 : ${licenseName}`);
      console.log(`  - Generated by Odoo    : ${generatedByOdoo}`);
      console.log(`  - Installer provider   : ${installerProvider}`);
      console.log(`  - Licensing            : ${licensing}`);
      console.log(`  - Expires              : ${expires}`);
      console.log(`  - Expire Mode          : ${expireMode === '' ? '(unset)' : expireMode}`);
      console.log(`  - Expiration Days shown: ${expirationDaysShown}`);
      console.log(`  - Expiration Days      : ${expirationDays === '' ? '(not rendered)' : expirationDays}`);
      console.log(`  - Expire Start shown   : ${expireStartDateShown}`);
      console.log(`  - Expire Start Date    : ${expireStartDate === '' ? '(empty)' : expireStartDate}`);
      console.log(`  - Expiration End shown : ${expirationEndDateShown}`);
      console.log(`  - Expiration End Date  : ${expirationEndDate === '' ? '(empty)' : expirationEndDate}`);
      console.log(`  - Maintenance Days     : ${maintenanceDays}`);

      await CommonUtils.captureAndAttachScreenshot(page, testInfo, `Steps to reproduce I - licence ${licenseId} generated by the WebShop job`);
    });

    // -------------------------------------------------------------------------------------------
    // Verification
    // -------------------------------------------------------------------------------------------
    await test.step('Verification: the automatically generated licence is Perpetual with Expires = never and expiration days = 0', async () => {
      const expirationDaysNumeric = parseInt((expirationDays || '0').replace(/[^\d-]/g, '') || '0', 10);
      const expirationDaysIsZero = expirationDays === '' || expirationDaysNumeric === 0;
      const maintenanceDaysNumeric = parseInt((maintenanceDays || '0').replace(/[^\d-]/g, '') || '0', 10);
      const nameCarriesInvoice = licenseName.includes(invoiceNumber);

      console.log('==================== VERIFY ====================');
      console.log('  Verify #1 - Generated by Odoo (marks the automatic WebShop path):');
      console.log('     Expected : true');
      console.log(`     Actual   : ${generatedByOdoo}`);
      console.log(`     Result   : ${generatedByOdoo === true ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #2 - Installer provider:');
      console.log(`     Expected : ${EXPECTED_INSTALLER_PROVIDER}`);
      console.log(`     Actual   : ${installerProvider}`);
      console.log(`     Result   : ${installerProvider === EXPECTED_INSTALLER_PROVIDER ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #3 - Licence belongs to the paid website invoice (name carries the invoice number):');
      console.log(`     Expected : contains "${invoiceNumber}"`);
      console.log(`     Actual   : ${licenseName}`);
      console.log(`     Result   : ${nameCarriesInvoice ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #4 - Licensing:');
      console.log(`     Expected : ${EXPECTED_LICENSING}`);
      console.log(`     Actual   : ${licensing}`);
      console.log(`     Result   : ${licensing === EXPECTED_LICENSING ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #5 - Expires:');
      console.log(`     Expected : ${EXPECTED_EXPIRES}`);
      console.log(`     Actual   : ${expires}`);
      console.log(`     Result   : ${expires === EXPECTED_EXPIRES ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #6 - Expire Mode:');
      console.log(`     Expected : ${EXPECTED_EXPIRE_MODE}`);
      console.log(`     Actual   : ${expireMode === '' ? '(unset)' : expireMode}`);
      console.log(`     Result   : ${expireMode === EXPECTED_EXPIRE_MODE ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #7 - Expiration Days value (365 = the reported defect):');
      console.log('     Expected : empty or 0');
      console.log(`     Actual   : ${expirationDays === '' ? '(not rendered)' : expirationDays}`);
      console.log(`     Result   : ${expirationDaysIsZero ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #8 - "Expiration Days" field displayed (Odoo hides it when Expires != in):');
      console.log('     Expected : NOT DISPLAYED');
      console.log(`     Actual   : ${expirationDaysShown ? 'DISPLAYED' : 'NOT DISPLAYED'}`);
      console.log(`     Result   : ${expirationDaysShown === false ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #9 - "Expire Start Date" field displayed / value:');
      console.log('     Expected : NOT DISPLAYED / empty');
      console.log(`     Actual   : ${expireStartDateShown ? 'DISPLAYED' : 'NOT DISPLAYED'} / ${expireStartDate === '' ? '(empty)' : expireStartDate}`);
      console.log(`     Result   : ${expireStartDateShown === false && expireStartDate === '' ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #10 - "Expiration End Date" field displayed / value:');
      console.log('     Expected : NOT DISPLAYED / empty');
      console.log(`     Actual   : ${expirationEndDateShown ? 'DISPLAYED' : 'NOT DISPLAYED'} / ${expirationEndDate === '' ? '(empty)' : expirationEndDate}`);
      console.log(`     Result   : ${expirationEndDateShown === false && expirationEndDate === '' ? 'PASS' : 'FAIL'}`);
      console.log('  Verify #11 - Maintenance Days (the SKU support days must land HERE, not in expiry):');
      console.log('     Expected : greater than 0');
      console.log(`     Actual   : ${maintenanceDays === '' ? '(not rendered)' : maintenanceDays}`);
      console.log(`     Result   : ${maintenanceDaysNumeric > 0 ? 'PASS' : 'FAIL'}`);
      console.log('===============================================');
      console.log(`OVERALL: licence #${licenseId} generated by the WebShop job for ${invoiceNumber} (${orderName}) - perpetual, no expiry stamped`);

      expect(generatedByOdoo, 'Generated by Odoo must be checked - the licence has to come from the automatic WebShop path')
        .toBe(true);
      expect(installerProvider, `Installer provider must be "${EXPECTED_INSTALLER_PROVIDER}"`)
        .toBe(EXPECTED_INSTALLER_PROVIDER);
      expect(nameCarriesInvoice, `The generated licence must belong to invoice ${invoiceNumber}, read "${licenseName}"`)
        .toBe(true);
      expect(licensing, `The generated licence must be "${EXPECTED_LICENSING}" - ${PERPETUAL_SKU} is a perpetual SKU`)
        .toBe(EXPECTED_LICENSING);
      expect(expires, `Expires must be "${EXPECTED_EXPIRES}" on a licence generated from a perpetual order`)
        .toBe(EXPECTED_EXPIRES);
      expect(expireMode, `Expire Mode must be "${EXPECTED_EXPIRE_MODE}" - the WebShop path stores NONE (evidence licence #149605)`)
        .toBe(EXPECTED_EXPIRE_MODE);
      expect(expirationDaysIsZero, `Expiration Days must be empty or 0, read "${expirationDays}" (365 = the reported defect)`)
        .toBe(true);
      expect(expirationDaysShown, 'The "Expiration Days" field must NOT be displayed while Expires = never')
        .toBe(false);
      expect(expireStartDateShown, 'The "Expire Start Date" field must NOT be displayed while Expire Mode = none')
        .toBe(false);
      expect(expireStartDate, 'Expire Start Date must stay empty on a perpetual licence')
        .toBe('');
      expect(expirationEndDateShown, 'The "Expiration End Date" field must NOT be displayed while Expire Mode = none')
        .toBe(false);
      expect(expirationEndDate, 'Expiration End Date must stay empty on a perpetual licence')
        .toBe('');
      expect(maintenanceDaysNumeric, `Maintenance Days must be greater than 0 - the SKU's support window belongs in the maintenance fields, read "${maintenanceDays}"`)
        .toBeGreaterThan(0);
    });
  });
});
